"""Public M02-03 identification raw-ingestion contracts."""

from glio_proteogen.contracts.m02_03.canonical import (
    canonical_request_digest,
    configuration_digest,
    policy_digest,
    result_payload_digest,
)
from glio_proteogen.contracts.m02_03.schema import ContractName, contract_json_schema
from glio_proteogen.contracts.m02_03.v1 import (
    M0203_AUTHORITY_LIMITATION_CODE,
    M0203_CONTRACT_VERSION,
    M0203_INGESTION_LIMITATION_CODE,
    M0203_MAX_SOURCES,
    M0203_MODULE_ID,
    BundleDiagnostic,
    BundleDiagnosticCode,
    IdentificationIngestionPolicy,
    IdentificationRawIngestionResult,
    IdentificationRawSource,
    IngestIdentificationRawInputsRequest,
    ParseDiagnostic,
    RawFormat,
    RawIngestionPolicy,
    RawInputDisposition,
    RawInputRole,
    RawSourceDescriptor,
    RoleFormatRequirement,
    RoleRequirement,
    ValidatedIdentificationRawInput,
    ValidatedRawInputDescriptor,
)

__all__ = [
    "M0203_AUTHORITY_LIMITATION_CODE",
    "M0203_CONTRACT_VERSION",
    "M0203_INGESTION_LIMITATION_CODE",
    "M0203_MAX_SOURCES",
    "M0203_MODULE_ID",
    "BundleDiagnostic",
    "BundleDiagnosticCode",
    "ContractName",
    "IdentificationIngestionPolicy",
    "IdentificationRawIngestionResult",
    "IdentificationRawSource",
    "IngestIdentificationRawInputsRequest",
    "ParseDiagnostic",
    "RawFormat",
    "RawIngestionPolicy",
    "RawInputDisposition",
    "RawInputRole",
    "RawSourceDescriptor",
    "RoleFormatRequirement",
    "RoleRequirement",
    "ValidatedIdentificationRawInput",
    "ValidatedRawInputDescriptor",
    "canonical_request_digest",
    "configuration_digest",
    "contract_json_schema",
    "policy_digest",
    "result_payload_digest",
]
