"""Research-only scientific foundations awaiting a frozen production ABI.

The package is deliberately separate from the contract modules.  It provides bounded,
reproducible primitives for inspecting public proteomics evidence, but it does not publish
protein, disease, or clinical claims and is not wired into the M03/M04 execution surfaces.
"""

from .cohort import (
    CohortGroupQc,
    CohortLabelContrast,
    CohortLabelGroupEvidence,
    CohortLabelQc,
    CohortQcPolicy,
    CohortSampleQc,
    CohortSampleScale,
    ResearchCohortRequest,
    ResearchCohortResult,
    ResearchCohortSample,
    aggregate_cohort_evidence,
    replay_research_cohort,
    run_research_cohort,
)
from .cohort_provenance import CohortSourceBinding, CohortSourceManifest
from .evidence import (
    EvidenceBundle,
    EvidenceQuality,
    EvidenceQualitySummary,
    EvidenceRecord,
    aggregate_evidence,
    verify_evidence_bundle,
)
from .evidence_aggregation import (
    ExternalEvidenceAggregate,
    ExternalEvidenceObservation,
    aggregate_external_evidence,
    replay_external_evidence,
)
from .fasta import (
    DEFAULT_FASTA_MAX_BYTES,
    DEFAULT_FASTA_MAX_ENTRIES,
    DEFAULT_FASTA_MAX_RESIDUES,
    FastaEntry,
    SearchSpace,
    build_search_space,
    digest_trypsin,
    read_fasta,
)
from .fasta import (
    SearchSpaceReceipt as GeneratedSearchSpaceReceipt,
)
from .modifications import (
    MODIFICATION_CATALOGUE_VERSION,
    ModificationSpec,
    ParsedPeptide,
    PeptideModification,
    expand_peptide,
    expand_peptide_map,
    modification_catalogue_digest,
    normalize_modification_rules,
    parse_modified_peptide,
    supported_modifications,
)
from .mzml import Spectrum, parse_mzml
from .pdc import (
    PdcClient,
    PdcFile,
    PdcSourceReceipt,
    PdcStudySnapshot,
    verify_pdc_source_content,
)
from .pilot import (
    PilotError,
    PilotLimits,
    PilotPolicy,
    PilotRequest,
    PilotResult,
    SignalProxy,
    result_json,
    run_pilot,
    verify_pilot_replay,
)
from .pipeline import (
    ResearchRunRequest,
    ResearchRunResult,
    bind_pdc_mzml_source,
    replay_research_protein_inference,
    run_research_protein_inference,
)
from .protein import (
    ProteinGroup,
    ProteinGroupCandidate,
    ProteinGroupFdrSummary,
    infer_protein_group_candidates,
    infer_protein_groups,
)
from .public_proteomics.formats import (
    MzIdentMlStructure,
    bind_mzidentml_references,
    extract_mzidentml_structure,
)
from .public_proteomics.provenance import SourceReference
from .quantification import (
    PeptideQuant,
    PeptideQuantification,
    ProteinGroupQuant,
    QuantificationPolicy,
    QuantificationReceipt,
    median_normalize,
    quantify_matched_ions,
    quantify_matched_ions_with_receipt,
    quantify_protein_groups,
)
from .search import (
    FdrSummary,
    Psm,
    PsmCompetition,
    SearchParameters,
    search_spectrum,
    search_spectrum_candidates,
    summarize_target_decoy,
    target_decoy_qvalues,
)
from .search_space import (
    DecoyPair,
    SearchSpaceReceipt,
    build_search_space_receipt,
    verify_search_space_receipt,
)

__all__ = [
    "DEFAULT_FASTA_MAX_BYTES",
    "DEFAULT_FASTA_MAX_ENTRIES",
    "DEFAULT_FASTA_MAX_RESIDUES",
    "MODIFICATION_CATALOGUE_VERSION",
    "CohortGroupQc",
    "CohortLabelContrast",
    "CohortLabelGroupEvidence",
    "CohortLabelQc",
    "CohortQcPolicy",
    "CohortSampleQc",
    "CohortSampleScale",
    "CohortSourceBinding",
    "CohortSourceManifest",
    "DecoyPair",
    "EvidenceBundle",
    "EvidenceQuality",
    "EvidenceQualitySummary",
    "EvidenceRecord",
    "ExternalEvidenceAggregate",
    "ExternalEvidenceObservation",
    "FastaEntry",
    "FdrSummary",
    "GeneratedSearchSpaceReceipt",
    "ModificationSpec",
    "MzIdentMlStructure",
    "ParsedPeptide",
    "PdcClient",
    "PdcFile",
    "PdcSourceReceipt",
    "PdcStudySnapshot",
    "PeptideModification",
    "PeptideQuant",
    "PeptideQuantification",
    "PilotError",
    "PilotLimits",
    "PilotPolicy",
    "PilotRequest",
    "PilotResult",
    "ProteinGroup",
    "ProteinGroupCandidate",
    "ProteinGroupFdrSummary",
    "ProteinGroupQuant",
    "Psm",
    "PsmCompetition",
    "QuantificationPolicy",
    "QuantificationReceipt",
    "ResearchCohortRequest",
    "ResearchCohortResult",
    "ResearchCohortSample",
    "ResearchRunRequest",
    "ResearchRunResult",
    "SearchParameters",
    "SearchSpace",
    "SearchSpaceReceipt",
    "SignalProxy",
    "SourceReference",
    "Spectrum",
    "aggregate_cohort_evidence",
    "aggregate_evidence",
    "aggregate_external_evidence",
    "bind_mzidentml_references",
    "bind_pdc_mzml_source",
    "build_search_space",
    "build_search_space_receipt",
    "digest_trypsin",
    "expand_peptide",
    "expand_peptide_map",
    "extract_mzidentml_structure",
    "infer_protein_group_candidates",
    "infer_protein_groups",
    "median_normalize",
    "modification_catalogue_digest",
    "normalize_modification_rules",
    "parse_modified_peptide",
    "parse_mzml",
    "quantify_matched_ions",
    "quantify_matched_ions_with_receipt",
    "quantify_protein_groups",
    "read_fasta",
    "replay_external_evidence",
    "replay_research_cohort",
    "replay_research_protein_inference",
    "result_json",
    "run_pilot",
    "run_research_cohort",
    "run_research_protein_inference",
    "search_spectrum",
    "search_spectrum_candidates",
    "summarize_target_decoy",
    "supported_modifications",
    "target_decoy_qvalues",
    "verify_evidence_bundle",
    "verify_pdc_source_content",
    "verify_pilot_replay",
    "verify_search_space_receipt",
]
