"""Independent GBM master-kinase signature-concordance research engine."""

from .catalog import is_pinned_phosphosite, master_kinase_catalog
from .contracts import (
    ALGORITHM_ID,
    ALGORITHM_PROFILE_ID,
    ALGORITHM_VERSION,
    MAX_BOOTSTRAPS,
    MAX_COMPUTATIONAL_WORK_UNITS,
    MAX_OBSERVATIONS,
    MAX_PERMUTATIONS,
    MAX_REPLAY_BYTES,
    MAX_REQUEST_BYTES,
    MAX_RESULT_BYTES,
    PROFILE_ID,
    AnalysisSupport,
    EdgeAblation,
    GbmSubtype,
    KinaseEvidence,
    KinaseEvidenceCounts,
    MasterKinaseAlgorithmConstants,
    MasterKinaseProfile,
    MasterKinaseProvenance,
    MasterKinaseRequest,
    MasterKinaseResult,
    MethodAgreement,
    MethodEstimate,
    PhosphositeDriver,
    PhosphositeEvidenceState,
    PhosphositeObservation,
    RankEnrichmentEstimate,
    ReplayVerificationRequest,
    ReplayVerificationResult,
    SourceMasterKinaseReference,
    StandardizedContrastReference,
    StateClassification,
    SubtypeAblation,
    SubtypeEvidence,
    SubtypeKinaseDriver,
    UnverifiedMasterKinaseResult,
    estimate_computational_work_units,
)
from .demo import DEMO_ID, build_demo_request, demo_request_digest, synthetic_demo_request
from .errors import CatalogIntegrityError, MasterKinaseError
from .integration import (
    ECGI_EXTERNAL_PROFILE_ID,
    ECGI_EXTERNAL_RANK_PROFILE_ID,
    MasterKinaseMethod,
    build_ecgi_external_kinase_profile,
)
from .profile import algorithm_profile
from .service import MasterKinaseService, analyze_master_kinases, verify_replay

__all__ = [
    "ALGORITHM_ID",
    "ALGORITHM_PROFILE_ID",
    "ALGORITHM_VERSION",
    "DEMO_ID",
    "ECGI_EXTERNAL_PROFILE_ID",
    "ECGI_EXTERNAL_RANK_PROFILE_ID",
    "MAX_BOOTSTRAPS",
    "MAX_COMPUTATIONAL_WORK_UNITS",
    "MAX_OBSERVATIONS",
    "MAX_PERMUTATIONS",
    "MAX_REPLAY_BYTES",
    "MAX_REQUEST_BYTES",
    "MAX_RESULT_BYTES",
    "PROFILE_ID",
    "AnalysisSupport",
    "CatalogIntegrityError",
    "EdgeAblation",
    "GbmSubtype",
    "KinaseEvidence",
    "KinaseEvidenceCounts",
    "MasterKinaseAlgorithmConstants",
    "MasterKinaseError",
    "MasterKinaseMethod",
    "MasterKinaseProfile",
    "MasterKinaseProvenance",
    "MasterKinaseRequest",
    "MasterKinaseResult",
    "MasterKinaseService",
    "MethodAgreement",
    "MethodEstimate",
    "PhosphositeDriver",
    "PhosphositeEvidenceState",
    "PhosphositeObservation",
    "RankEnrichmentEstimate",
    "ReplayVerificationRequest",
    "ReplayVerificationResult",
    "SourceMasterKinaseReference",
    "StandardizedContrastReference",
    "StateClassification",
    "SubtypeAblation",
    "SubtypeEvidence",
    "SubtypeKinaseDriver",
    "UnverifiedMasterKinaseResult",
    "algorithm_profile",
    "analyze_master_kinases",
    "build_demo_request",
    "build_ecgi_external_kinase_profile",
    "demo_request_digest",
    "estimate_computational_work_units",
    "is_pinned_phosphosite",
    "master_kinase_catalog",
    "synthetic_demo_request",
    "verify_replay",
]
